spring.application.name=spring_security
spring.main.allow-bean-definition-overriding=true
spring.datasource.url = jdbc:postgresql://localhost:5432/user
spring.datasource.username=postgres
spring.datasource.password=admin